# Generated by Django 4.2.3 on 2023-07-19 14:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_full_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_pick_them_up', models.BooleanField()),
                ('enable_chain_custody', models.BooleanField()),
                ('pickup_date', models.DateField()),
                ('single_location', models.BooleanField()),
            ],
        ),
    ]
